# XPATH LOCATORS
xpath_btn_sign_in = "//button[text()='Sign In']"
xpath_link_profile = "//a[@href='/panel/profile']"
xpath_input_email = "//input[@name='email']"
xpath_input_password = "//input[@name='password']"
xpath_btn_submit_sign_in = "//button[@type='submit' and text()='Sign In']"
xpath_logo_image = "//div[@class='header']//img[@alt='logo']"
xpath_navbar_link_garage_text = "//ul[contains(@class, 'navbar-nav')]//a[text()='Garage']"
xpath_navbar_link_garage_href = "//ul[contains(@class, 'navbar-nav')]//a[contains(@href, '/garage')]"
xpath_heading_garage = "//h1[contains(text(), 'Garage')]"
xpath_btn_add_car = "//button[contains(@class, 'btn-primary') and contains(text(), 'Add car')]"
xpath_input_brand = "//label[text()='Brand']/following-sibling::div//input"
xpath_input_model = "//label[text()='Model']/following-sibling::div//input"
xpath_input_mileage = "//label[text()='Mileage']/following-sibling::div//input"
xpath_btn_submit_add = "//form//button[@type='submit' and contains(text(), 'Add')]"
xpath_car_card_title = "//div[contains(@class, 'garage-car')]//h2"
xpath_car_card_mileage = "//div[contains(@class, 'garage-car')]//p[contains(text(), 'mileage')]"
xpath_alert_success = "//div[contains(@class, 'alert') and contains(text(), 'successfully')]"
xpath_nav_link_settings = "//nav//a[text()='Settings']"
xpath_link_history = "//a[@href='/panel/history']"
xpath_link_car_service = "//a[text()='Car service']"
xpath_dropdown_logout = "//div[@class='dropdown-menu show']//a[text()='Logout']"
xpath_btn_create_new_car = "//button[contains(text(), 'Create new car')]"
xpath_input_brand_next = "//label[contains(text(), 'Brand')]/following::input[1]"
xpath_input_mileage_next = "//label[contains(text(), 'Mileage')]/following::input[1]"
xpath_input_number_field = "//div[@class='form-group']//input[@type='number']"

# CSS LOCATORS
css_btn_sign_in = "button:contains('Sign In')"
css_link_profile = "a[href='/panel/profile']"
css_input_email = "input[name='email']"
css_input_password = "input[name='password']"
css_btn_submit = "button[type='submit']"
css_logo_image = "div.header img[alt='logo']"
css_navbar_link_garage = "ul.navbar-nav a[href*='/garage']"
css_heading_garage = "h1:contains('Garage')"
css_btn_primary = "button.btn-primary"
css_input_brand = "label:contains('Brand') + div input"
css_input_model = "label:contains('Model') + div input"
css_input_mileage = "label:contains('Mileage') + div input"
css_btn_form_submit = "form button[type='submit']"
css_car_card_title = "div.garage-car h2"
css_car_card_mileage = "div.garage-car p"
css_alert = "div.alert"
css_nav_link_settings = "nav a[href='/panel/settings']"
css_link_history = "a[href='/panel/history']"
css_link_car_service = "a[href='/panel/car-service']"
css_dropdown_logout = "div.dropdown-menu.show a[href='/logout']"
css_btn_create_car = "button.create-car-button"
css_input_brand_sibling = "label:contains('Brand') ~ input"
css_input_mileage_sibling = "label:contains('Mileage') ~ input"
css_input_number = "div.form-group input[type='number']"
css_navbar_logo = "header .navbar-brand"
