# XPATH LOCATORS
"//button[text()='Sign In']"
"//a[@href='/panel/profile']"
"//input[@name='email']"
"//input[@name='password']"
"//button[@type='submit' and text()='Sign In']"
"//div[@class='header']//img[@alt='logo']"
"//ul[contains(@class, 'navbar-nav')]//a[text()='Garage']"
"//ul[contains(@class, 'navbar-nav')]//a[contains(@href, '/garage')]"
"//h1[contains(text(), 'Garage')]"
"//button[contains(@class, 'btn-primary') and contains(text(), 'Add car')]"
"//label[text()='Brand']/following-sibling::div//input"
"//label[text()='Model']/following-sibling::div//input"
"//label[text()='Mileage']/following-sibling::div//input"
"//form//button[@type='submit' and contains(text(), 'Add')]"
"//div[contains(@class, 'garage-car')]//h2"
"//div[contains(@class, 'garage-car')]//p[contains(text(), 'mileage')]"
"//div[contains(@class, 'alert') and contains(text(), 'successfully')]"
"//nav//a[text()='Settings']"
"//a[@href='/panel/history']"
"//a[text()='Car service']"
"//div[@class='dropdown-menu show']//a[text()='Logout']"
"//button[contains(text(), 'Create new car')]"
"//label[contains(text(), 'Brand')]/following::input[1]"
"//label[contains(text(), 'Mileage')]/following::input[1]"
"//div[@class='form-group']//input[@type='number']"

# CSS LOCATORS
"button:contains('Sign In')"
"a[href='/panel/profile']"
"input[name='email']"
"input[name='password']"
"button[type='submit']"
"div.header img[alt='logo']"
"ul.navbar-nav a[href*='/garage']"
"h1:contains('Garage')"
"button.btn-primary"
"label:contains('Brand') + div input"
"label:contains('Model') + div input"
"label:contains('Mileage') + div input"
"form button[type='submit']"
"div.garage-car h2"
"div.garage-car p"
"div.alert"
"nav a[href='/panel/settings']"
"a[href='/panel/history']"
"a[href='/panel/car-service']"
"div.dropdown-menu.show a[href='/logout']"
"button.create-car-button"
"label:contains('Brand') ~ input"
"label:contains('Mileage') ~ input"
"div.form-group input[type='number']"
"header .navbar-brand"
