version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    user: root
    environment:
      - TZ=Europe/Warsaw

    command: >
      bash -c "apt-get update &&
               apt-get install -y python3 python3-pip python3-venv &&
               /usr/local/bin/jenkins.sh"

volumes:
  jenkins_home: