pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/nastasiaKN/pythonAQA.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run tests') {
            steps {
                sh 'pytest --alluredir=allure-results'
            }
        }

        stage('Allure Report') {
            steps {
                allure includeProperties: false, jdk: '', results: [[path: 'allure-results']]
            }
        }
    }

    post {
        always {
            mail to: 'InsertYour@Mail.Here',
                 subject: "Pipeline result: ${currentBuild.fullDisplayName}",
                 body: "Build ${currentBuild.result}: ${env.BUILD_URL}"
        }
    }
}